import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import ManualModelDetectionDialog from '../ManualModelDetectionDialog.vue'
import { getAvailableModels } from '@/api/admin/accounts'
import { modelDetectionAPI } from '@/api/admin/modelDetection'

vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
vi.mock('@/api/admin/accounts', () => ({ getAvailableModels: vi.fn() }))
vi.mock('@/api/admin/modelDetection', () => ({ modelDetectionAPI: { runAccount: vi.fn(), catalog: vi.fn() } }))
const render = () => mount(ManualModelDetectionDialog, { props: { show: true, account: { id: 17, name: '测试账号' } }, global: { stubs: { BaseDialog: { template: '<section><slot /></section>' } } } })

describe('账号手动模型检测', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    vi.mocked(getAvailableModels).mockResolvedValue([{ id: 'model-a', display_name: '模型 A', type: 'model', created_at: '' }])
    vi.mocked(modelDetectionAPI.runAccount).mockResolvedValue({ id: 4 } as never)
    vi.mocked(modelDetectionAPI.catalog).mockResolvedValue({ reference_models: [{ id: 'gpt-4o', display_name: 'GPT-4o', family: 'openai' }], suite_version: 'v1', requests_per_run: 4 })
  })
  it('打开弹窗不调用模型，手动提交使用所选账号和自填模型且不创建或开启定时任务', async () => {
    const wrapper = render()
    await flushPromises()
    expect(getAvailableModels).toHaveBeenCalledWith(17)
    expect(modelDetectionAPI.runAccount).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('modelDetection.costHint')
    await wrapper.get('input').setValue(' custom-model ')
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(modelDetectionAPI.runAccount).toHaveBeenCalledTimes(1)
    expect(modelDetectionAPI.runAccount).toHaveBeenCalledWith(17, 'custom-model', '')
    expect(wrapper.emitted('queued')).toHaveLength(1)
    expect(wrapper.emitted('close')).toHaveLength(1)
    wrapper.unmount()
  })
  it('可选模型列表加载失败仍允许手动输入模型，保留后端原始错误', async () => {
    vi.mocked(getAvailableModels).mockRejectedValue(new Error('模型接口暂不可用'))
    vi.mocked(modelDetectionAPI.runAccount).mockRejectedValue({ message: '该账号不支持此模型' })
    const wrapper = render()
    await flushPromises()
    expect(wrapper.text()).toContain('modelDetection.modelsUnavailable')
    await wrapper.get('input').setValue('model-x')
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toBe('该账号不支持此模型')
    expect(wrapper.emitted('close')).toBeUndefined()
    wrapper.unmount()
  })
  it('提交中防止重复发起，不允许切走对话框', async () => {
    let resolve: ((value: never) => void) | undefined
    vi.mocked(modelDetectionAPI.runAccount).mockImplementation(() => new Promise(done => { resolve = done }))
    const wrapper = render()
    await flushPromises()
    await wrapper.get('input').setValue('model-a')
    await wrapper.get('form').trigger('submit')
    await wrapper.get('form').trigger('submit')
    expect(modelDetectionAPI.runAccount).toHaveBeenCalledTimes(1)
    expect(wrapper.get('button[type="button"]').attributes('disabled')).toBeDefined()
    resolve?.({ id: 1 } as never)
    await flushPromises()
    wrapper.unmount()
  })
  it('切换账号时丢弃旧账号的模型列表', async () => {
    let resolve: ((value: Awaited<ReturnType<typeof getAvailableModels>>) => void) | undefined
    vi.mocked(getAvailableModels).mockImplementationOnce(() => new Promise(done => { resolve = done }))
    const wrapper = render()
    await wrapper.setProps({ account: { id: 18, name: '另一个账号' } })
    await flushPromises()
    resolve?.([{ id: 'old-model', display_name: '旧模型', type: 'model', created_at: '' }])
    await flushPromises()
    expect(wrapper.findAll('datalist option').map(option => option.attributes('value'))).toEqual(['model-a'])
    wrapper.unmount()
  })
  it('别名模型可以指定本轮参考模型，实际模型 ID 与参考模型分别传递', async () => {
    const wrapper = render()
    await flushPromises()
    await wrapper.get('input').setValue('my-model-alias')
    await wrapper.get('select').setValue('gpt-4o')
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(modelDetectionAPI.runAccount).toHaveBeenCalledWith(17, 'my-model-alias', 'gpt-4o')
    wrapper.unmount()
  })
  it('参考库接口失败时仍允许本轮能力检测，不要求开启计划', async () => {
    vi.mocked(modelDetectionAPI.catalog).mockRejectedValue(new Error('不可用'))
    const wrapper = render()
    await flushPromises()
    expect(wrapper.text()).toContain('modelDetection.catalogUnavailable')
    await wrapper.get('input').setValue('custom-model')
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(modelDetectionAPI.runAccount).toHaveBeenCalledWith(17, 'custom-model', '')
    expect(wrapper.emitted('queued')).toHaveLength(1)
    wrapper.unmount()
  })
})
