import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import ManualModelDetectionDialog from '../ManualModelDetectionDialog.vue'
import { getAvailableModels } from '@/api/admin/accounts'
import { modelDetectionAPI } from '@/api/admin/modelDetection'

vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string, params?: unknown) => params ? `${key} ${JSON.stringify(params)}` : key }) }))
vi.mock('@/api/admin/accounts', () => ({ getAvailableModels: vi.fn() }))
vi.mock('@/api/admin/modelDetection', () => ({ modelDetectionAPI: { runAccountModels: vi.fn(), catalog: vi.fn() } }))
const render = () => mount(ManualModelDetectionDialog, { props: { show: true, account: { id: 17, name: '测试账号' } }, global: { stubs: { BaseDialog: { template: '<section><slot /><footer><slot name="footer" /></footer></section>' } } } })
const successResult = (models: string[]) => ({ total: models.length, success: models.length, failed: 0, results: models.map(model_id => ({ model_id, run: { id: 4 } as never })) })

async function addCustom(wrapper: ReturnType<typeof render>, model: string) {
  await wrapper.get('[data-testid="custom-model"]').setValue(model)
  await wrapper.get('[data-testid="custom-model"]').trigger('keydown', { key: 'Enter' })
}

describe('账号手动模型检测', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    vi.mocked(getAvailableModels).mockResolvedValue(['model-a', 'model-b'].map(id => ({ id, display_name: id, type: 'model', created_at: '' })))
    vi.mocked(modelDetectionAPI.runAccountModels).mockImplementation(async (_id, models) => successResult(models))
    vi.mocked(modelDetectionAPI.catalog).mockResolvedValue({ reference_models: [], suite_version: 'v1', requests_per_run: 4, request_timeout_seconds: 600 })
  })
  it('多选现有和自定义模型，一次批量提交，不要求另设参考或启用定时任务', async () => {
    const wrapper = render()
    await flushPromises()
    expect(getAvailableModels).toHaveBeenCalledWith(17)
    expect(modelDetectionAPI.runAccountModels).not.toHaveBeenCalled()
    expect(wrapper.find('select').exists()).toBe(false)
    await wrapper.get('input[value="model-a"]').setValue(true)
    await addCustom(wrapper, ' custom-model ')
    expect(wrapper.text()).toContain('"count":8')
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(modelDetectionAPI.runAccountModels).toHaveBeenCalledTimes(1)
    expect(modelDetectionAPI.runAccountModels).toHaveBeenCalledWith(17, ['model-a', 'custom-model'])
    expect(wrapper.emitted('queued')).toHaveLength(1)
    expect(wrapper.emitted('close')).toHaveLength(1)
    wrapper.unmount()
  })
  it('异步读取模型显示加载状态，底部检测按钮仍关联原表单', async () => {
    let resolve!: (value: Awaited<ReturnType<typeof getAvailableModels>>) => void
    vi.mocked(getAvailableModels).mockImplementationOnce(() => new Promise(done => { resolve = done }))
    const wrapper = render()
    expect(wrapper.get('[role="status"]').text()).toBe('common.loading')
    expect(wrapper.text()).not.toContain('modelDetection.noModelMatches')
    const submit = wrapper.get<HTMLButtonElement>('footer button[type="submit"]')
    expect(submit.attributes('form')).toBe(wrapper.get('form').attributes('id'))
    expect(submit.element.disabled).toBe(true)
    resolve([{ id: 'loaded-model', display_name: '已加载模型', type: 'model', created_at: '' }])
    await flushPromises()
    expect(wrapper.find('[role="status"]').exists()).toBe(false)
    await wrapper.get('input[value="loaded-model"]').setValue(true)
    expect(submit.element.disabled).toBe(false)
    wrapper.unmount()
  })
  it('可选模型列表失败仍可自填，保留后端原始错误及选择', async () => {
    vi.mocked(getAvailableModels).mockRejectedValue(new Error('模型接口暂不可用'))
    vi.mocked(modelDetectionAPI.runAccountModels).mockRejectedValue({ message: '该账号不支持此模型' })
    const wrapper = render()
    await flushPromises()
    expect(wrapper.text()).toContain('modelDetection.modelsUnavailable')
    await addCustom(wrapper, 'model-x')
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toBe('该账号不支持此模型')
    expect(wrapper.get('[data-testid="selected-models"]').text()).toContain('model-x')
    expect(wrapper.emitted('close')).toBeUndefined()
    wrapper.unmount()
  })
  it('提交中防止重复发起，并禁止关闭对话框', async () => {
    let resolve: ((value: Awaited<ReturnType<typeof modelDetectionAPI.runAccountModels>>) => void) | undefined
    vi.mocked(modelDetectionAPI.runAccountModels).mockImplementation(() => new Promise(done => { resolve = done }))
    const wrapper = render()
    await flushPromises()
    await wrapper.get('input[value="model-a"]').setValue(true)
    await wrapper.get('form').trigger('submit')
    await wrapper.get('form').trigger('submit')
    expect(modelDetectionAPI.runAccountModels).toHaveBeenCalledTimes(1)
    expect(wrapper.findAll('button').find(button => button.text() === 'modelDetection.cancel')!.attributes('disabled')).toBeDefined()
    resolve?.(successResult(['model-a']))
    await flushPromises()
    wrapper.unmount()
  })
  it('切换账号时丢弃旧模型列表和选择', async () => {
    let resolve: ((value: Awaited<ReturnType<typeof getAvailableModels>>) => void) | undefined
    vi.mocked(getAvailableModels).mockImplementationOnce(() => new Promise(done => { resolve = done }))
    const wrapper = render()
    await wrapper.setProps({ account: { id: 18, name: '另一个账号' } })
    await flushPromises()
    resolve?.([{ id: 'old-model', display_name: '旧模型', type: 'model', created_at: '' }])
    await flushPromises()
    expect(wrapper.findAll('input[type="checkbox"]').map(input => input.attributes('value'))).toEqual(['model-a', 'model-b'])
    expect(wrapper.find('[data-testid="selected-models"]').exists()).toBe(false)
    wrapper.unmount()
  })
  it('部分失败显示具体模型错误，重试只发送失败模型', async () => {
    vi.mocked(modelDetectionAPI.runAccountModels).mockResolvedValueOnce({ total: 2, success: 1, failed: 1, results: [{ model_id: 'model-a', run: { id: 9 } as never }, { model_id: 'model-b', error: '该模型已有运行任务', reason: 'MODEL_DETECTION_BUSY' }] })
    const wrapper = render()
    await flushPromises()
    await wrapper.get('input[value="model-a"]').setValue(true)
    await wrapper.get('input[value="model-b"]').setValue(true)
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('model-b: 该模型已有运行任务')
    expect(wrapper.get('[data-testid="selected-models"]').text()).toContain('model-b')
    expect(wrapper.get('[data-testid="selected-models"]').text()).not.toContain('model-a')
    expect(wrapper.emitted('close')).toBeUndefined()
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(modelDetectionAPI.runAccountModels).toHaveBeenLastCalledWith(17, ['model-b'])
    expect(wrapper.emitted('queued')).toHaveLength(2)
    expect(wrapper.emitted('close')).toHaveLength(1)
    wrapper.unmount()
  })
  it('目录接口失败不会阻止检测，按默认每模型四次显示消耗提示', async () => {
    vi.mocked(modelDetectionAPI.catalog).mockRejectedValue(new Error('不可用'))
    const wrapper = render()
    await flushPromises()
    await addCustom(wrapper, 'custom-model')
    expect(wrapper.text()).toContain('"count":4')
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(modelDetectionAPI.runAccountModels).toHaveBeenCalledWith(17, ['custom-model'])
    expect(wrapper.emitted('queued')).toHaveLength(1)
    wrapper.unmount()
  })
})
